version: '3.7'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
      - /tmp/log:/home/app/web/midata:ro
    ports:
      - 80:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django_dev_db_un
      - POSTGRES_PASSWORD=hello_django_db_pw
      - POSTGRES_DB=hello_django_dev_db

volumes:
  postgres_data:
