version: '3.7'

services:
  nginx:
    build: ./nginx

    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - $HOME/midata/public:/home/app/web/midata
    ports:
      # external:internal (host:container)
      - 80:80
    depends_on:
      - web

  web:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    command: gunicorn main_app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - "static_volume:/home/app/web/staticfiles"
      - "media_volume:/home/app/web/mediafiles"
    expose: # only exposed to other local docker containers
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - elasticsearch

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db.prod

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: es
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200


volumes:
  postgres_data:
  static_volume:
  media_volume:
  midata:
  esdata1:


