version: '3.7'

services:
  # nginx:
  #   build: ./nginx
  #   volumes:
  #     - static_volume:/home/app/web/staticfiles
  #     - media_volume:/home/app/web/mediafiles
  #     - $HOME/midata/public:/home/app/web/midata
  #   ports:
  #     # external:internal (host:container)
  #     - 80:80
  #   depends_on:
  #     - web

  web:
    restart: always
    build:
      context: ./elasticproject
      dockerfile: Dockerfile
    container_name: django-qary
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./elasticproject/:/usr/src/elasticproject/
    ports: # only exposed to other local docker containers
      - 8000:8000
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:7.6.1
    container_name: elasticsearch-qary
    volumes:
      - ./elasticsearch-docker/esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9300:9300"
      - "9200:9200"


volumes:
  
  # static_volume:
  # media_volume:
  elasticproject:
  # midata:
  esdata:


