version: "3.7"

services:

  web:
    build: .
    container_name: django-es
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    networks: 
      - elastic-net
    ports:
      - 8000:8000
    expose:
      - 8000
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: es
    volumes:
      - //c/dev/tools/elasticsearch-7.6.1/data:/code/esdata
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    networks:
      - elastic-net
    ports:
      - "9200:9200"
      - "9300:9300"

volumes:
  django-project:
  esdata:

networks:
  elastic-net: